DROP TABLE IF EXISTS users, friends, images, tags;

CREATE TABLE users(
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL
);

CREATE TABLE friends(
    id SERIAL PRIMARY KEY,
    user_id INT NOT NULL REFERENCES users ON DELETE CASCADE,
    friend_id INT NOT NULL REFERENCES users ON DELETE CASCADE
);

CREATE TABLE images(
    id SERIAL PRIMARY KEY,
    user INT NOT NULL REFERENCES users ON DELETE CASCADE,
);

CREATE TABLE tags(
    id SERIAL PRIMARY KEY ,
    image_id INT NOT NULL REFERENCES images ON DELETE CASCADE,
    tagged INT NOT NULL REFERENCES users ON DELETE CASCADE
);